name: PHP Code Quality Diagnostics

on: [push]

env:
  PHPCQ_DIRECTORY: ./phpcq-runner

jobs:
  build:
    runs-on: ubuntu-latest

    name: PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        php: [ 7.3, 7.4 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug2

      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --prefer-dist
        env:
          COMPOSER_ROOT_VERSION: dev-master

      - name: Update phpcq
        run: $GITHUB_WORKSPACE/vendor/bin/phpcq self-update

      - name: Install phpcq toolchain
        run: $GITHUB_WORKSPACE/vendor/bin/phpcq install -v --trust-keys

      - name: Run tests
        run: $GITHUB_WORKSPACE/vendor/bin/phpcq run -v -o default
